### PR TITLE
Add libraries

### LINKED ISSUE #13: add dependencies
--------
Issue Description
--------

**Is your feature request related to a problem? Please describe.**
Add Spacy and NLTK libraries for nature language processing 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

### PR DESCRIPTION
**Pull request by wangcj05**
Add Spacy and NLTK for nature language processing capabilities, close #13

### CODE REVIEW

**Review by mandd — COMMENTED** [review]
should we update also the dependency list?

**Comment by wangcj05** [comment]
Currently, we do not have a module use these two libraries yet. I would suggest to update our documents when we start to create a module that use these libraries.

**Comment by mandd** [comment]
> Currently, we do not have a module use these two libraries yet. I would suggest to update our documents when we start to create a module that use these libraries.

This is why I could not find such document. Let's put this task in our todo list.

**Review by mandd — DISMISSED** [review]

**Comment by wangcj05** [comment]
I have opened an issue #15

**Comment by wangcj05** [comment]
This PR can be closed.

**Pull request closed without merging**
